# sudo: required

services:
  - docker

# env:
#   DOCKER_COMPOSE_VERSION: 1.23.2

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

before_script:
  - docker-compose up -d --build

script: 
  - docker-compose run test

after_script:
  - docker-compose down